const router = require('express').Router();
const { param } = require('express-validator');
const { authenticate } = require('../middlewares/auth.middleware');
const { validate } = require('../middlewares/validation.middleware');
const controller = require('../controllers/notification.controller');
const idValidator = [param('id').isInt({ min: 1 }).withMessage('Notification ID must be a positive integer').toInt()];
router.use(authenticate);
router.get('/', controller.list);
router.get('/unread-count', controller.unreadCount);
router.patch('/read-all', controller.markAllRead);
router.patch('/:id/read', idValidator, validate, controller.markRead);
router.delete('/:id', idValidator, validate, controller.remove);
module.exports = router;
